### ISSUE TITLE
multipart/form-data integration?

### ISSUE THREAD

**Issue by AndrewSB** [kean/Get#79]
I didn't see an example of how to do this, i'm using MultipartFormDataKit & what i'm doing is
```swift
return Future {
    let filename = UUID().uuidString
    let boundary = RandomBoundaryGenerator.generate()
    let multipartFormData = try MultipartFormDataKit.MultipartFormData.Builder.build(
        with: [(
            name: "file",
            filename: "\(filename).png",
            mimeType: MIMEType.imagePng,
            data: data
        )],
        willSeparateBy: boundary
    ).body

    return try await self.apiStore.send(Paths.me.picture.patch(multipartFormData), configure: {
        $0.setValue("multipart/form-data; boundary=\(boundary)", forHTTPHeaderField: "Content-Type")
    }).value
}
```

but it feels a little verbose at the callsite. my swagger definition says that the form should contain data at the key `file`, for example

is this the expected integration? or is there something a little less verbose?

**Comment by kean** [comment]
It looks good, but one thing I would look for is making sure you are not passing the binary data (`Data`) in the methods that accept `Decodable`. By default, `JSONDecoder` encodes binary data using `base64`, which is not what you want in most cases. I think you are good in this case, because [`APIClient/send`](https://kean-docs.github.io/get/documentation/get/apiclient/send(_:delegate:configure:)-3t9w0) doesn't use `JSONDecoder` when you pass `Data`.

For other questions, I'd suggest following the [MultipartFormDataKit](https://github.com/Kuniwak/MultipartFormDataKit) docs. Get is a micro-framework: there is nothing built-in by design.

**Comment by AndrewSB** [comment]
appreciate the lookover, and all the other work you put out @kean!

**Comment by zabojad** [comment]
@AndrewSB Hi ! Could you please tell me what `Paths.me.picture.patch` does ? Can you share its code ?
